### ISSUE TITLE
Download Youtube apk directly from apkmirror not from google drive.

### ISSUE THREAD

**Issue by kazimmt** [Jarvis-Ank/Re-Vanced#15]
Can you please download the apk file directly from apkmirror instead google drive.
It'll save everyone's time.

Thank you for your hard work.

**Comment by Bartek20** [comment]
I have already made such an attempt, however, the apkmirror site is protected by cloudflare which blocks all requests to access files from headless machines (including google colab script). I know that in a certain project creators managed to achieve this and after finishing work on the script logs I will analyze their code and try to apply it in this project.
