### ISSUE TITLE
Protected Branch

### ISSUE THREAD

**Issue by Bartek20** [Jarvis-Ank/Re-Vanced#17]
@Jarvis-Ank could you disable the protected branch in the repository, because I can't make changes directly in the main branch, but I have to create separate ones for each patch.

**Comment by Jarvis-Ank** [comment]
@Bartek20 hey check it out now.. i've added push permissions for you. that should work.

**Comment by Bartek20** [comment]
Unfortunately it didn't change anything, from what I found out you can give me some "bypass branch protections" role and it should work. More information you have [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)

**Comment by Bartek20** [comment]
Maybe this will allow me to make changes in main branch.
https://github.com/Jarvis-Ank/Re-Vanced/settings/branch_protection_rules/new
![image](https://user-images.githubusercontent.com/67280540/190419913-a8705634-626b-466f-b025-be134b9e6953.png)

**Comment by Bartek20** [comment]
I read a bit and to add this role "bypass branch protections" is the account to which the repository belongs to have to belong to the organization.

But I found a way to make changes. You only need to disable the code review requirement and then I will be able to merge my pull requests.

**Comment by Jarvis-Ank** [comment]
it comes with security issues. i think we'll keep it as it is now. i'll try to check PR more often.

**Comment by Bartek20** [comment]
Then maybe you will add my 2nd test account as a collaborator and then I will be able to give myself reviews.
