### ISSUE TITLE
link error .. and capturing file

### ISSUE THREAD

**Issue by ronschlockett** [Jarvis-Ank/Re-Vanced#2]
1/Using the instructions copying the link GDrive provides will give you a filenotfound error - it actually explains this in the code result but the average pleb will not even see this.  Link has to be structured like https://drive.google.com/uc?id=...file..id.. which you can easily just add in your file id from the link first provided https://drive.google.com/file/d/.....file...id..here../view?usp=sharing

2/ most that are probably going to use this are prob not going to have any clue as to how to get the file once it has run completely - I added this before the rm folder command - it copies file to your gdrive main dir  (remove " from 1st and 4th lines)
 
"# mount it"  
from google.colab import drive
drive.mount('/content/drive')
"# copy it there"
!cp revanced.apk "/content/drive/My Drive/"

Awesome work tho btw, thx 4 spending the time to he rid us of those ****** ads

**Comment by Jarvis-Ank** [comment]
I've thought of that, didn't get time to add it. I'll add that soon.. thanks for pointing out.

**Comment by ronschlockett** [comment]
Actually this would probably be better closing loose ends.  Thx again!

from google.colab import drive
!cp revanced.apk "/content/drive/My Drive/"
from google.colab import drive
drive.flush_and_unmount ('/content/drive')

**Comment by Jarvis-Ank** [comment]
> Actually this would probably be better closing loose ends.  Thx again!
> 
> from google.colab import drive
> !cp revanced.apk "/content/drive/My Drive/"
> from google.colab import drive
> drive.flush_and_unmount ('/content/drive')
> 

Yes, but one of the main problem would be to convince people so that they don't feel like compromising their security. Many wouldn't consider loging in although it is only linking to their own Colab account.
